/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CaseStep {
  'id' : bigint,
  'narrative' : string,
  'phase' : Phase,
  'currentVitals' : Vitals,
  'choices' : Array<Choice>,
}
export type Category = { 'obstetrics' : null } |
  { 'trauma' : null } |
  { 'airwayEmergency' : null } |
  { 'paediatrics' : null } |
  { 'cardiac' : null } |
  { 'generalSurgery' : null };
export interface Choice {
  'id' : bigint,
  'explanation' : string,
  'text' : string,
  'guidelineRef' : string,
  'isCorrect' : boolean,
  'vitalChanges' : Vitals,
}
export interface Debrief {
  'scenarioId' : bigint,
  'score' : Score,
  'steps' : Array<DebriefStep>,
  'sessionId' : bigint,
}
export interface DebriefStep {
  'stepId' : bigint,
  'explanation' : string,
  'correctAnswer' : Choice,
  'guidelineRef' : string,
  'chosenAnswer' : Choice,
}
export interface PatientInfo {
  'age' : bigint,
  'weight' : number,
  'asaGrade' : bigint,
  'relevantHistory' : string,
}
export type Phase = { 'emergence' : null } |
  { 'induction' : null } |
  { 'crisis' : null } |
  { 'maintenance' : null } |
  { 'preOp' : null };
export interface Scenario {
  'id' : bigint,
  'title' : string,
  'difficulty' : bigint,
  'description' : string,
  'steps' : Array<CaseStep>,
  'patientInfo' : PatientInfo,
  'category' : Category,
}
export interface Score {
  'total' : bigint,
  'correct' : bigint,
  'incorrect' : bigint,
}
export interface StepResult {
  'wasCorrect' : boolean,
  'explanation' : string,
  'guidelineRef' : string,
  'updatedVitals' : Vitals,
  'isComplete' : boolean,
}
export interface Vitals {
  'hr' : bigint,
  'rr' : bigint,
  'dbp' : bigint,
  'sbp' : bigint,
  'spo2' : bigint,
  'temp' : number,
  'etco2' : bigint,
}
export interface _SERVICE {
  'getDebrief' : ActorMethod<[bigint], Debrief>,
  'getScenarios' : ActorMethod<[], Array<Scenario>>,
  'getStep' : ActorMethod<[bigint], CaseStep>,
  'initializeScenarios' : ActorMethod<[], undefined>,
  'resetSession' : ActorMethod<[bigint], undefined>,
  'startSession' : ActorMethod<[bigint], [bigint, CaseStep]>,
  'submitAnswer' : ActorMethod<[bigint, bigint], StepResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];