/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Score = IDL.Record({
  'total' : IDL.Nat,
  'correct' : IDL.Nat,
  'incorrect' : IDL.Nat,
});
export const Vitals = IDL.Record({
  'hr' : IDL.Nat,
  'rr' : IDL.Nat,
  'dbp' : IDL.Nat,
  'sbp' : IDL.Nat,
  'spo2' : IDL.Nat,
  'temp' : IDL.Float64,
  'etco2' : IDL.Nat,
});
export const Choice = IDL.Record({
  'id' : IDL.Nat,
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'guidelineRef' : IDL.Text,
  'isCorrect' : IDL.Bool,
  'vitalChanges' : Vitals,
});
export const DebriefStep = IDL.Record({
  'stepId' : IDL.Nat,
  'explanation' : IDL.Text,
  'correctAnswer' : Choice,
  'guidelineRef' : IDL.Text,
  'chosenAnswer' : Choice,
});
export const Debrief = IDL.Record({
  'scenarioId' : IDL.Nat,
  'score' : Score,
  'steps' : IDL.Vec(DebriefStep),
  'sessionId' : IDL.Nat,
});
export const Phase = IDL.Variant({
  'emergence' : IDL.Null,
  'induction' : IDL.Null,
  'crisis' : IDL.Null,
  'maintenance' : IDL.Null,
  'preOp' : IDL.Null,
});
export const CaseStep = IDL.Record({
  'id' : IDL.Nat,
  'narrative' : IDL.Text,
  'phase' : Phase,
  'currentVitals' : Vitals,
  'choices' : IDL.Vec(Choice),
});
export const PatientInfo = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'asaGrade' : IDL.Nat,
  'relevantHistory' : IDL.Text,
});
export const Category = IDL.Variant({
  'obstetrics' : IDL.Null,
  'trauma' : IDL.Null,
  'airwayEmergency' : IDL.Null,
  'paediatrics' : IDL.Null,
  'cardiac' : IDL.Null,
  'generalSurgery' : IDL.Null,
});
export const Scenario = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'difficulty' : IDL.Nat,
  'description' : IDL.Text,
  'steps' : IDL.Vec(CaseStep),
  'patientInfo' : PatientInfo,
  'category' : Category,
});
export const StepResult = IDL.Record({
  'wasCorrect' : IDL.Bool,
  'explanation' : IDL.Text,
  'guidelineRef' : IDL.Text,
  'updatedVitals' : Vitals,
  'isComplete' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getDebrief' : IDL.Func([IDL.Nat], [Debrief], ['query']),
  'getScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
  'getStep' : IDL.Func([IDL.Nat], [CaseStep], ['query']),
  'initializeScenarios' : IDL.Func([], [], []),
  'resetSession' : IDL.Func([IDL.Nat], [], []),
  'startSession' : IDL.Func([IDL.Nat], [IDL.Nat, CaseStep], []),
  'submitAnswer' : IDL.Func([IDL.Nat, IDL.Nat], [StepResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Score = IDL.Record({
    'total' : IDL.Nat,
    'correct' : IDL.Nat,
    'incorrect' : IDL.Nat,
  });
  const Vitals = IDL.Record({
    'hr' : IDL.Nat,
    'rr' : IDL.Nat,
    'dbp' : IDL.Nat,
    'sbp' : IDL.Nat,
    'spo2' : IDL.Nat,
    'temp' : IDL.Float64,
    'etco2' : IDL.Nat,
  });
  const Choice = IDL.Record({
    'id' : IDL.Nat,
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'guidelineRef' : IDL.Text,
    'isCorrect' : IDL.Bool,
    'vitalChanges' : Vitals,
  });
  const DebriefStep = IDL.Record({
    'stepId' : IDL.Nat,
    'explanation' : IDL.Text,
    'correctAnswer' : Choice,
    'guidelineRef' : IDL.Text,
    'chosenAnswer' : Choice,
  });
  const Debrief = IDL.Record({
    'scenarioId' : IDL.Nat,
    'score' : Score,
    'steps' : IDL.Vec(DebriefStep),
    'sessionId' : IDL.Nat,
  });
  const Phase = IDL.Variant({
    'emergence' : IDL.Null,
    'induction' : IDL.Null,
    'crisis' : IDL.Null,
    'maintenance' : IDL.Null,
    'preOp' : IDL.Null,
  });
  const CaseStep = IDL.Record({
    'id' : IDL.Nat,
    'narrative' : IDL.Text,
    'phase' : Phase,
    'currentVitals' : Vitals,
    'choices' : IDL.Vec(Choice),
  });
  const PatientInfo = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'asaGrade' : IDL.Nat,
    'relevantHistory' : IDL.Text,
  });
  const Category = IDL.Variant({
    'obstetrics' : IDL.Null,
    'trauma' : IDL.Null,
    'airwayEmergency' : IDL.Null,
    'paediatrics' : IDL.Null,
    'cardiac' : IDL.Null,
    'generalSurgery' : IDL.Null,
  });
  const Scenario = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'difficulty' : IDL.Nat,
    'description' : IDL.Text,
    'steps' : IDL.Vec(CaseStep),
    'patientInfo' : PatientInfo,
    'category' : Category,
  });
  const StepResult = IDL.Record({
    'wasCorrect' : IDL.Bool,
    'explanation' : IDL.Text,
    'guidelineRef' : IDL.Text,
    'updatedVitals' : Vitals,
    'isComplete' : IDL.Bool,
  });
  
  return IDL.Service({
    'getDebrief' : IDL.Func([IDL.Nat], [Debrief], ['query']),
    'getScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
    'getStep' : IDL.Func([IDL.Nat], [CaseStep], ['query']),
    'initializeScenarios' : IDL.Func([], [], []),
    'resetSession' : IDL.Func([IDL.Nat], [], []),
    'startSession' : IDL.Func([IDL.Nat], [IDL.Nat, CaseStep], []),
    'submitAnswer' : IDL.Func([IDL.Nat, IDL.Nat], [StepResult], []),
  });
};

export const init = ({ IDL }) => { return []; };