/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CaseStep {
    id: bigint;
    narrative: string;
    phase: Phase;
    currentVitals: Vitals;
    choices: Array<Choice>;
}
export interface Vitals {
    hr: bigint;
    rr: bigint;
    dbp: bigint;
    sbp: bigint;
    spo2: bigint;
    temp: number;
    etco2: bigint;
}
export interface Debrief {
    scenarioId: bigint;
    score: Score;
    steps: Array<DebriefStep>;
    sessionId: bigint;
}
export interface Scenario {
    id: bigint;
    title: string;
    difficulty: bigint;
    description: string;
    steps: Array<CaseStep>;
    patientInfo: PatientInfo;
    category: Category;
}
export interface Score {
    total: bigint;
    correct: bigint;
    incorrect: bigint;
}
export interface PatientInfo {
    age: bigint;
    weight: number;
    asaGrade: bigint;
    relevantHistory: string;
}
export interface Choice {
    id: bigint;
    explanation: string;
    text: string;
    guidelineRef: string;
    isCorrect: boolean;
    vitalChanges: Vitals;
}
export interface DebriefStep {
    stepId: bigint;
    explanation: string;
    correctAnswer: Choice;
    guidelineRef: string;
    chosenAnswer: Choice;
}
export interface StepResult {
    wasCorrect: boolean;
    explanation: string;
    guidelineRef: string;
    updatedVitals: Vitals;
    isComplete: boolean;
}
export enum Category {
    obstetrics = "obstetrics",
    trauma = "trauma",
    airwayEmergency = "airwayEmergency",
    paediatrics = "paediatrics",
    cardiac = "cardiac",
    generalSurgery = "generalSurgery"
}
export enum Phase {
    emergence = "emergence",
    induction = "induction",
    crisis = "crisis",
    maintenance = "maintenance",
    preOp = "preOp"
}
export interface backendInterface {
    getDebrief(sessionId: bigint): Promise<Debrief>;
    getScenarios(): Promise<Array<Scenario>>;
    getStep(sessionId: bigint): Promise<CaseStep>;
    initializeScenarios(): Promise<void>;
    resetSession(sessionId: bigint): Promise<void>;
    startSession(scenarioId: bigint): Promise<[bigint, CaseStep]>;
    submitAnswer(sessionId: bigint, choiceId: bigint): Promise<StepResult>;
}
import type { CaseStep as _CaseStep, Category as _Category, Choice as _Choice, PatientInfo as _PatientInfo, Phase as _Phase, Scenario as _Scenario, Vitals as _Vitals } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getDebrief(arg0: bigint): Promise<Debrief> {
        if (this.processError) {
            try {
                const result = await this.actor.getDebrief(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDebrief(arg0);
            return result;
        }
    }
    async getScenarios(): Promise<Array<Scenario>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScenarios();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScenarios();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStep(arg0: bigint): Promise<CaseStep> {
        if (this.processError) {
            try {
                const result = await this.actor.getStep(arg0);
                return from_candid_CaseStep_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStep(arg0);
            return from_candid_CaseStep_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeScenarios(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeScenarios();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeScenarios();
            return result;
        }
    }
    async resetSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetSession(arg0);
            return result;
        }
    }
    async startSession(arg0: bigint): Promise<[bigint, CaseStep]> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(arg0);
                return [
                    result[0],
                    from_candid_CaseStep_n5(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(arg0);
            return [
                result[0],
                from_candid_CaseStep_n5(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async submitAnswer(arg0: bigint, arg1: bigint): Promise<StepResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CaseStep_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseStep): CaseStep {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Phase_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Phase): Phase {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Scenario_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Scenario): Scenario {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    difficulty: bigint;
    description: string;
    steps: Array<_CaseStep>;
    patientInfo: _PatientInfo;
    category: _Category;
}): {
    id: bigint;
    title: string;
    difficulty: bigint;
    description: string;
    steps: Array<CaseStep>;
    patientInfo: PatientInfo;
    category: Category;
} {
    return {
        id: value.id,
        title: value.title,
        difficulty: value.difficulty,
        description: value.description,
        steps: from_candid_vec_n4(_uploadFile, _downloadFile, value.steps),
        patientInfo: value.patientInfo,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    narrative: string;
    phase: _Phase;
    currentVitals: _Vitals;
    choices: Array<_Choice>;
}): {
    id: bigint;
    narrative: string;
    phase: Phase;
    currentVitals: Vitals;
    choices: Array<Choice>;
} {
    return {
        id: value.id,
        narrative: value.narrative,
        phase: from_candid_Phase_n7(_uploadFile, _downloadFile, value.phase),
        currentVitals: value.currentVitals,
        choices: value.choices
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    obstetrics: null;
} | {
    trauma: null;
} | {
    airwayEmergency: null;
} | {
    paediatrics: null;
} | {
    cardiac: null;
} | {
    generalSurgery: null;
}): Category {
    return "obstetrics" in value ? Category.obstetrics : "trauma" in value ? Category.trauma : "airwayEmergency" in value ? Category.airwayEmergency : "paediatrics" in value ? Category.paediatrics : "cardiac" in value ? Category.cardiac : "generalSurgery" in value ? Category.generalSurgery : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emergence: null;
} | {
    induction: null;
} | {
    crisis: null;
} | {
    maintenance: null;
} | {
    preOp: null;
}): Phase {
    return "emergence" in value ? Phase.emergence : "induction" in value ? Phase.induction : "crisis" in value ? Phase.crisis : "maintenance" in value ? Phase.maintenance : "preOp" in value ? Phase.preOp : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Scenario>): Array<Scenario> {
    return value.map((x)=>from_candid_Scenario_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CaseStep>): Array<CaseStep> {
    return value.map((x)=>from_candid_CaseStep_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
